### ISSUE TITLE
A request

### ISSUE THREAD

**Issue by qianwang102** [kaylani2/machineLearning#7]

**Comment by kaylani2** [comment]
Hello, qianwang102. Your request is "Could you please share your code about the multiclass classification of bot-iot dataset?"

Sadly we do not have any examples of multiclass classification in the bot-iot dataset. This is because we needed to perform binary classification in our paper to provide comparable results between models and datasets.

However, it should be easy enough to use the code written for binary classification and adapt to multiclass classification. You'll mainly need to change the target and the network's outputs to match the correct shape. Naturally the hyperparameters will need to be adjusted as well.

**Comment by qianwang102** [comment]
Sorry to bother you.I have already tried it with your code and I have got the result. I just don't know how to delete this issue .
Thanks for your sharing！
